name = "JuliaRegistry"
uuid = "84c61fbd-64a4-4993-a634-90f682c6af21"
repo = "https://github.com/Atomtomate/JuliaRegistry"
description = "Private JulaRegistry"

[packages]
d262d690-7b73-43ed-8cf8-7b23904776e1 = { name = "SeriesAcceleration", path = "S/SeriesAcceleration" }
